# Java Gradle CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
    working_directory: ~/code
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - run:
        name: Write api key to local properties
        command: echo "tmdb_api_key=some_key_here" > ${HOME}/local.properties

      - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

        
      # run tests!
      - run: gradle test
